[package]
name = "lsamp"
version = "0.1.4"
edition = "2021"
license = "MIT"
authors = ["Alex Genco <alexgenco@gmail.com>"]
description = "Sample stdin at a fixed rate"

[dependencies]

[dev-dependencies]
rand = "0.8"
